databases:
  - name: postgres
    ipAllowList: []
    plan: free
    user: tima

services:
  - type: web
    plan: free
    name: tima
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tima
          property: connectionString